name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      TF_VAR_environment: "dev"
      TF_VAR_region: "us-east-1"
      TF_VAR_ami_id: "ami-0aa7d40eeae50c9a9"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9

    - uses: DamianReeves/write-file-action@master
      with:
        path: backend.tf
        contents: |
          terraform {
            backend "s3" {
              bucket = "${{ secrets.BUCKET_NAME }}"
              key    = "state/terraform.tfstate"
              region = "us-east-1"
            }
          }
        write-mode: overwrite

    - name: Verify Backend.tf
      run: |
        ls -R
        cat backend.tf

    - name: Terraform Init
      run: terraform init

    - name: Debug
      run: echo "$GITHUB_REF"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master'
      run: terraform apply -auto-approve -input=false
